name: Build Plugins
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        run: gradle make
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds
          folder: build
